# Generated by Django 2.2.1 on 2019-06-09 12:01

from django.db import migrations, models
import vid4.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic_file',
        ),
        migrations.AddField(
            model_name='picture',
            name='picfile',
            field=models.ImageField(default=1, upload_to=vid4.models.image_folder),
            preserve_default=False,
        ),
    ]
